#cria o banco se não existir
spring.datasource.url=mysql://g4l2jytq45wuwq4i:iwoge3fag7ebklf9@cdm1s48crk8itlnr.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/ue90tet72ek943kz

#para criar o banco no MySQL
spring.jpa.hibernate.ddl-auto=none
#para mostrar as consultas SQL
spring.jpa.show-sql=false
#para formatar as consultas SQL
spring.jpa.properties.hibernate.format_sql=false
