spring.profiles.active=test


#Email
default.sender=mjgomes1978@gmail.com
default.recipient=mjgomes1978@gmail.com

#JWT
jwt.secret=SequenciaDeCaracteresParaAssinaturaDoToken
jwt.expiration=86400000

#AWS S3
s3.bucket=dev-ionic
aws.region=sa-east-1

# AWS
aws.access-key-id=
aws.secret-access-key=

