spring.profiles.active=test


#Email
default.sender=mjgomes1978@gmail.com
default.recipient=mjgomes1978@gmail.com

#JWT
jwt.secret=SequenciaDeCaracteresParaAssinaturaDoTokenSuperSecretaComMaisDe64CaracteresParaOAlgoritmoHS512
jwt.expiration=600000
