#cria o banco se não existir
spring.datasource.url=jdbc:mysql://localhost:3306/curso_spring
spring.datasource.username=root
spring.datasource.password=#Mysql139710

#para criar o banco no MySQL
spring.jpa.hibernate.ddl-auto=create
#para mostrar as consultas SQL
spring.jpa.show-sql=true
#para formatar as consultas SQL
spring.jpa.properties.hibernate.format_sql=true


spring.mail.host=smtp.gmail.com
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth = true
spring.mail.properties.mail.smtp.socketFactory.port = 465
spring.mail.properties.mail.smtp.socketFactory.class = javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.smtp.socketFactory.fallback = false
spring.mail.properties.mail.smtp.starttls.enable = true
spring.mail.properties.mail.smtp.ssl.enable = true